version: "3.9"

volumes:
  cht-credentials:
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/prometheus/data
      o: bind

services:
  couchdb.1:
    image: public.ecr.aws/medic/cht-couchdb:4.1.0-alpha
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - ${DB1_DATA:-./couch/data/srv1}:/opt/couchdb/data
      - cht-credentials:/opt/couchdb/etc/local.d/
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET:-6c1953b6-e64d-4b0c-9268-2528396f2f58}
      - COUCHDB_UUID=${COUCHDB_UUID:-5c265815-b9e3-47f1-ba8d-c1d50495eeb2}
      - SVC_NAME=${SVC1_NAME:-couchdb.1}
      - COUCHDB_LOG_LEVEL=${COUCHDB_LOG_LEVEL:-error}
    logging:
      driver: local
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILES:-20}
    restart: unless-stopped
    networks:
      cht-net:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      cht-net:
    restart: unless-stopped

  couchdb-prometheus-exporter:
    image: gesellix/couchdb-prometheus-exporter
    command: --couchdb.uri=http://couchdb.1:5984 --logtostderr --couchdb.username=${COUCHDB_USER} --couchdb.password=${COUCHDB_PASSWORD} --databases=_all_dbs
    ports:
      # Optional - for accessing the exporter's metric documentation
      - "9984:9984"
    networks:
      cht-net:
    restart: unless-stopped

networks:
  cht-net:
    name: ${CHT_NETWORK:-cht-net}
